### ISSUE TITLE
Other cities/state location also shown in suggestion list when I searching the location in Bangalore city

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/BI_Web_App#11]
Show the search suggestion list based on that particular view. 

Check the screenshot,

![search](https://user-images.githubusercontent.com/44860646/51909998-f373fa00-23f3-11e9-9bdf-b3d0a7bbade2.png)

**Comment by naveenjayabalan** [comment]
Suppose you are in Bangalore  city level data watching you want move Delhi city data. search the data and move quickly. so only listed all datas
