### ISSUE TITLE
In Secondary sales -->Discovery -->Sales, I didn't get the result when I selecting the "Combine -- Retailer ". 

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/BI_Web_App#29]
If i select the combine --> Retailer (No's) in India level, the system just loading but nothing happens. 

Check the screenshot,

![load](https://user-images.githubusercontent.com/44860646/52056538-8e054200-2588-11e9-83aa-b6cc906b9702.png)

**Comment by naveenjayabalan** [comment]
retailers will work for(city,ward,N.brhd) levels only. we will show the msg as soon as possible
