### ISSUE TITLE
In secondary sales--> Discovery --> sales, District name missing in the chart window. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/BI_Web_App#30]
Check the screenshot,

![dist](https://user-images.githubusercontent.com/44860646/52058939-7fba2480-258e-11e9-95fa-3c44352cabf1.png)

**Comment by naveenjayabalan** [comment]
Check this case again. if you get the correct results close this issues

**Comment by VigneshBI** [comment]
This is fixed.
