### ISSUE TITLE
In MKT potential --> Demographic Segment --> Profile individual, I Didn't get the result when filtering the two (or) more categories. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/BI_Web_App#5]
If I select the "Urban-Rural & Gender" category and click on the Combine / Split button, it shows "data not available" error message instead of a result. please check it

Check the screenshot,
![result](https://user-images.githubusercontent.com/44860646/51890565-619fc900-23c2-11e9-8adc-983e7d8c9b4f.png)

**Comment by naveenjayabalan** [comment]
Results are coming. If you did't get result please call any one of us
